add get redirect without html
gladly-team/tab-homepage pull request #157
Opened 2021-05-17 20:11 UTC by amaliwanag2

2021-05-17 20:34 UTC, amaliwanag2 commented
end 2 end tests passed on browser stack, need to adjust timeout in tab-e2e

2021-05-17 22:56 UTC, kmjennison requested changes

2021-05-17 22:56 UTC, kmjennison commented on src/utils/__tests__/redirect.test.js
> +  it('redirects to the Firefox Add-ons page when the browser is Firefox on desktop', () => {
Update test description

2021-05-17 22:56 UTC, kmjennison commented on src/utils/__tests__/redirect.test.js
> +  it('redirects to the Firefox Add-ons page when the browser is Firefox on mobile', () => {
Update test description

2021-05-17 22:56 UTC, kmjennison commented on src/pages/__tests__/get.test.js
> +    expect(directToAppExtension).toHaveBeenCalled()
A better test: mock a return URL for `directToAppExtension`, then assert redirect is called with that URL.

2021-05-17 22:56 UTC, kmjennison commented on src/pages/__tests__/cats-get.test.js
> +    expect(directToAppExtension).toHaveBeenCalled()
A better test: mock a return URL for `directToAppExtension`, then assert redirect is called with that URL.

2021-05-18 21:13 UTC, amaliwanag2 commented
@kmjennison you can see the ui on dev at http://dev-tab2017.gladly.io/cats/getHTML

2021-05-21 00:17 UTC, kmjennison requested changes
Functional problem: the unsupported browser redirects to the main homepage but should redirect to `/cats/`.

Aesthetic preference for users: instead of `/cats/getHTML/`, how about: `/cats/get/intro/`?

2021-05-21 00:17 UTC, kmjennison commented
Content for the timer redirect looks great, BTW 👍

2021-06-02 18:13 UTC, kmjennison requested changes

2021-06-02 18:13 UTC, kmjennison commented on src/pages/cats/get.js
> +      redirect(directToAppExtension())
Needs to go to cats page: `directToAppExtension(true)`

2021-06-22 22:18 UTC, kmjennison approved these changes
LGTM 🦊

2021-06-22 22:18 UTC, merged